### ISSUE TITLE
2.0.353执行SQL时导致内存操作错误？

### ISSUE THREAD

**Issue by newbarton** [IoTSharp/EntityFrameworkCore.Taos#133]
CreateCommand时报以下错误：
System.AccessViolationException
  HResult=0x80004003
  Message=Attempted to read or write protected memory. This is often an indication that other memory is corrupt.
  Source=<无法计算异常源>
  StackTrace:
<无法计算异常堆栈跟踪>
换回2.0.304后正常。
另外，根据2.0.2.0提供的新的客户端接口函数taos_subscribe、taos_insert_lines、taos_open_stream能否增加新的功能？例如采用类似SqlBulkCopy函数实现数据批复制，方便数据迁移或备份恢复？

**Comment by maikebing** [comment]
没有应用场景 ， 所以暂时没列到计划内。

**Comment by maikebing** [comment]
测试新版本有这个问题吗？ @newbarton

**Comment by weiwxg** [comment]
现在依然存在问题

**Comment by maikebing** [comment]
能上传个演示问题的例子嘛？

**Comment by weiwxg** [comment]
这个很难上传例子呀，我这边的场景表明，触发的条件似乎是和数据量有关系，当一个表数据量比较大时，多次执行一个耗时的操作，比如说group by 子句中包含一个普通Field，那么这个操作的效率就会非常低，这时候就很容易触发上述指针问题

**Comment by maikebing** [comment]
能拿到 StackTrace 嘛？

**Comment by weiwxg** [comment]
```c#
Fatal error. System.AccessViolationException: Attempted to read or write protected memory. This is often an indication that other memory is corrupt. Repeat 2 times: -------------------------------- at TDengineDriver.TDengine.StopQuery(IntPtr) -------------------------------- at IoTSharp.Data.Taos.TaosCommand.ExecuteReader(System.Data.CommandBehavior) at CurveTask.Utils.KukaTelemetryUtils.Run(IoTSharp.Data.Taos.TaosConnectionStringBuilder) at CurveTask.HostRun+<>c__DisplayClass3_0+<<Start>b__1>d.MoveNext()
```

**Comment by weiwxg** [comment]
[issue 4691](https://github.com/taosdata/TDengine/issues/4691)
还有一种情况是类似于这个issue，在一个定时器里执行一个普通查询，也有概率触发这个问题

**Comment by maikebing** [comment]
@sangshuduo

**Comment by maikebing** [comment]
2.6.2 会有这个问题嘛？

**Comment by weiwxg** [comment]
我们现在的版本是2.4.0.33
