### ISSUE TITLE
内存泄露

### ISSUE THREAD

**Issue by lpgitaccount** [IoTSharp/EntityFrameworkCore.Taos#169]
你好，作者，我在使用过程中发现，执行sql一直报错的话，非托管内存持续增长

**Comment by maikebing** [comment]
提供一个样例？

**Comment by lpgitaccount** [comment]
你好！这是我测试的demo
[Test.Taos.zip](https://github.com/IoTSharp/EntityFrameworkCore.Taos/files/8697425/Test.Taos.zip)

**Comment by lpgitaccount** [comment]
好的，上面那个文件可能加密了，看这个吧
[Test.Taos.zip](https://github.com/IoTSharp/EntityFrameworkCore.Taos/files/8706475/Test.Taos.zip)

**Comment by maikebing** [comment]
新版本有测试吗？

**Comment by maikebing** [comment]
最新的是 IoTSharp.Data.Taos   4.0.478

**Comment by maikebing** [comment]
开始之前内存:3699224,总计新增:43005024，当前内存:28383184
回收后:23482064

**Comment by maikebing** [comment]
@pigwing
