### ISSUE TITLE
版本升级后插入数据失败

### ISSUE THREAD

**Issue by weiwxg** [IoTSharp/EntityFrameworkCore.Taos#192]
在升了.NET6的驱动版本（`IoTSharp.EntityFrameworkCore.Taos` V2.0.453）后，插入报错，请问是什么问题（测试之前的`Maikebing.EntityFrameworkCore.Taos`版本没问题）
![image](https://user-images.githubusercontent.com/24971860/163108809-cab3c781-82be-40bd-a115-37671e2651fa.png)

**Comment by maikebing** [comment]
传个例子， 还有客户端， 服务端的版本号。

**Comment by maikebing** [comment]
新版本只验证过  TD 2.4.0.12

**Comment by weiwxg** [comment]
例子传不了了，被回滚了，td的客户端和服务端版本号是2.4.0.4

**Comment by pigwing** [comment]
试过在Linux上没,windows上的驱动确实问题非常多,这个感觉是.NET底层是utf16,没转成utf8的问题导致的.

**Comment by weiwxg** [comment]
![微信图片_20220414111613](https://user-images.githubusercontent.com/24971860/163306794-2b787f14-6100-415c-80c2-5fe2de368c76.png)
左边部分是最新版本的代码，执行操作的签名为byte字节数组
右边为以前的版本的代码
经测试，右边版本的代码没有报错，左边最新版本的代码报错

**Comment by pigwing** [comment]
对,因为tdengine改了驱动.所以你只能升级到最新的tdengine,毕竟是调用动态库的...驱动得跟着动态库变

**Comment by maikebing** [comment]
后期发布， 版本号 待跟官方驱动一直， 这样不会混淆。 你试试新版本2.4.0.12会不会有这个问题

**Comment by weiwxg** [comment]
有个问题问一下，我看你的代码中调用的`TDengineDriver.dll`和官方在`github`上放的`C# Demo`调用的版本似乎不一样，请问你的`TDEngineDriver.dll`是怎么来的，官方调用的这个版本里`Query`的方法签名只有这一个，并且通过它插入不会抛异常：
```c#
public static IntPtr Query(IntPtr conn, string command);
```
而你最终调用的是这个签名：
```c#
static extern private IntPtr Query(IntPtr conn, IntPtr byteArr);
```

**Comment by pigwing** [comment]
https://github.com/taosdata/TDengine/blob/develop/src/connector/C%23/src/TDengineDriver/TDengineDriver.cs#L228
这是官方最新的驱动版本
