### ISSUE TITLE
IoTSharp.Data.Taos.TaosCommand内存问题

### ISSUE THREAD

**Issue by aprilyush** [IoTSharp/EntityFrameworkCore.Taos#193]
从老版本Maikebing.Data.Taos更新到新的IoTSharp.Data.Taos后，程序内存一直涨降不下来，使用Windbg分析了一下dump文件 发现
00007ffe8de93548     2705       129840 System.Text.StringBuilder
00007ffe8e42b5d8        2       161344 System.Int64[]
00007ffe8dc96860     1943       229792 System.Object[]
00007ffe8dd57a90    10176      1005538 System.String
00007ffe8de16e18     3686      1147906 System.Char[]
00007ffe8e428c60      377      1517048 GatewayServer.TDengineConsumer.rtags[]
000000be0a5a0440     1495      2013680      Free
00007ffe8e4fe038        3      2129992 System.WeakReference`1[[IoTSharp.Data.Taos.TaosCommand, IoTSharp.Data.Taos]][]
00007ffe8dd9bf30     5799      4081100 System.Byte[]
00007ffe8e4fc8e8   216800      5203200 System.WeakReference`1[[IoTSharp.Data.Taos.TaosCommand, IoTSharp.Data.Taos]]
有多大20w的taosCommand个对象未释放，请教下 是和这个有关系吗。
程序只是从老版本更新了这个驱动，其他的逻辑基本没变化。

**Comment by maikebing** [comment]
最新版本的有改吗？另外版本有什么版本？

**Comment by maikebing** [comment]
你反馈的这个问题 @pigwing 提交过pr，新版本的 IoTSharp.EntityFrameworkCore.Taos 解决了。

**Comment by aprilyush** [comment]
> 

使用的版本IoTSharp.Data.Taos[2.0.453]，直接用的这个自己拼sql操作的，没用使用 IoTSharp.EntityFrameworkCore.Taos
下周一我更新一下IoTSharp.Data.Taos[2.0.467] 试试 感谢大佬回复

**Comment by aprilyush** [comment]
更新版本好像正常了 good,感谢大佬

**Comment by maikebing** [comment]
OK 。
