### ISSUE TITLE
内存会泄露

### ISSUE THREAD

**Issue by MrSe7enPlus** [IoTSharp/EntityFrameworkCore.Taos#225]
您好，
       在使用时发现内存泄露的情况，我写了一个timer，每20秒查询一次，发现查询完成后，内存也会随之变大，无法释放。
![image](https://user-images.githubusercontent.com/25544839/184313808-2d8fe047-da2b-48d8-a3cc-e1e20bf019a0.png)
![image](https://user-images.githubusercontent.com/25544839/184313850-5b0cf2aa-73ef-4062-b259-8ff35579fccc.png)

从一开始的42 后面 每查询一次就内存就变大。

**Comment by maikebing** [comment]
reader释放一下试试看。

**Comment by MrSe7enPlus** [comment]
![image](https://user-images.githubusercontent.com/25544839/184319384-3ab6219a-d9c2-4eb9-bdb0-8d06ad2a0ebb.png)
直接这样？

**Comment by maikebing** [comment]
是的。 你试试

**Comment by maikebing** [comment]
这个问题你在处理后 解决了嘛？

**Comment by MrSe7enPlus** [comment]
> 这个问题你在处理后 解决了嘛？

已经解决，谢谢。
