### ISSUE TITLE
数据库连接错误

### ISSUE THREAD

**Issue by Jiang4794** [IoTSharp/EntityFrameworkCore.Taos#226]
` using (TaosConnection conn = DataBase.TDConnect())
                {
                    conn.Open();
                    #region 原始数据数据插入
                    string tableName = "a_" + channels.AcquisitSerialNumber + "_" + channels.ChannelNumber + "_" + channels.SampleRate;
                    int channleId = int.Parse(channels.ChannelNumber.Replace("AI", ""));
                    StringBuilder stringBuilder = new StringBuilder();
                    long timestamp = GetTimestamp(DateTime.Now);
                    int rows = (count / 15000) + (count % 15000 == 0 ? 0 : 1);
                    switch (channels.ChannelNumber)
                    {
                        case "AI0":
                            for (int j = 0; j < rows; j++)
                            {
                                int oneRow = j == rows - 1 ? count % 15000 : 15000;
                                for (int i = 0; i < oneRow; i++)
                                {
                                    double orginal = 0;
                                    while (!Params.CKDataPackagelist[channels.AcquisitSerialNumber].AI0.TryDequeue(out orginal)) ;

                                    stringBuilder.Append("(" + timestamp + "," + orginal + ")");
                                    timestamp++;
                                    doubles[j * 15000 + i] = orginal;
                                }
                                conn.CreateCommand("insert into " + tableName + " using acceleration TAGS ('" + channels.AcquisitSerialNumber + "','" + channels.ChannelNumber + "'," + channels.SampleRate + ") VALUES " + stringBuilder).ExecuteNonQuery();
                                stringBuilder.Clear();
                            }
                            break;                      
                        default:
                            break;
                    }
                    _logger.LogTrace($"{DateTime.Now.TimeOfDay}：{channels.ChannelNumber}数据插入成功");
                    conn.Close();
                }`
多线程调用该方法，两秒钟调用一次，每次插入六万条数据；
使用版本：2.0.478
错误日志：
![image](https://user-images.githubusercontent.com/59756068/184565942-cc0a73b2-b1ef-4c9d-8516-a0ed4de7287f.png)

出现这个错误的原因可能是什么？

**Comment by Jiang4794** [comment]
![image](https://user-images.githubusercontent.com/59756068/184565876-1520e075-1667-44df-99eb-931ec416a754.png)

**Comment by maikebing** [comment]
不太好定位 ，资源耗尽？连接不可用？
 你试试最新版本 IoTSharp.Data.Taos  2.6.2 支持线程池的方式。 我测试一万条没问题。

**Comment by Jiang4794** [comment]
`            try
            {
                string taos = "DataSource=192.168.1.88;DataBase=onlineanalysis;Username=root;Password=kkny.com888;Port=6030";
                Task.Run(() =>
                {
                    while (true)
                    {
                        using (TaosConnection connection = TDConnect())
                        {
                            connection.Open();
                            Console.WriteLine($"{DateTime.Now.TimeOfDay}线程1连接成功");
                            connection.Close();
                        }
                    }
                });
                Task.Run(() =>
                {
                    while (true)
                    {
                        using (TaosConnection connection = TDConnect())
                        {
                            connection.Open();
                            Console.WriteLine($"{DateTime.Now.TimeOfDay}线程2连接成功");
                            connection.Close();
                        }
                    }
                });

                Task.Run(() =>
                {
                    while (true)
                    {
                        using (TaosConnection connection = TDConnect())
                        {
                            connection.Open();
                            Console.WriteLine($"{DateTime.Now.TimeOfDay}线程3连接成功");
                            connection.Close();
                        }
                    }
                });
            }
            catch(Exception ex)
            {
                Console.WriteLine(ex.Message);
            }`
现在在做数据采集，数据量超级大，这是一个三个线程的简单示例；
错误日志：
![image](https://user-images.githubusercontent.com/59756068/184594949-1194a4b8-deb2-4d91-b52e-c23000acf30d.png)

**Comment by maikebing** [comment]
建议你看下 我示例里面多线程的写法。 看改成 我那种写法 有没有问题，  你这种写法我没测试过。

**Comment by Jiang4794** [comment]
可以给我发一下示例的链接吗？我没有找到

**Comment by maikebing** [comment]
https://github.com/IoTSharp/EntityFrameworkCore.Taos/blob/64aaacd803b9f8fecbe9e9235089500ec6d442b2/src/Example/Program.cs#L97

**Comment by maikebing** [comment]
新版本已经处理线程池问题
