### ISSUE TITLE
Connection Open报错

### ISSUE THREAD

**Issue by weiwxg** [IoTSharp/EntityFrameworkCore.Taos#228]
![飞书20220829-085326](https://user-images.githubusercontent.com/24971860/187103085-6cb0f01c-861e-4a3d-befc-6df788d78511.jpg)
查询有几率报上述错误，经检查定位到最终的错误代码可能是在[TaosConnection](https://github.com/IoTSharp/EntityFrameworkCore.Taos/blob/master/src/IoTSharp.Data.Taos/TaosConnection.cs) 的203行的`Open`方法报的错，能给排查下具体是什么问题导致的吗？

**Comment by maikebing** [comment]
新版本已经解决了这个问题。

**Comment by maikebing** [comment]
但还没发布。
