### ISSUE TITLE
Attempted to read or write protected memory

### ISSUE THREAD

**Issue by Jiang4794** [IoTSharp/EntityFrameworkCore.Taos#232]
执行插入时提示错误
![55a8242c4d0f30e02fc50b56985efd8](https://user-images.githubusercontent.com/59756068/201501517-494900d9-a94e-4a9d-9e14-f74e08cc6be9.jpg)

**Comment by maikebing** [comment]
有完整的测试代码吗？如果是在项目中， 可否提供一个可以复现的代码？
