### ISSUE TITLE
使用taoscontext时报错

### ISSUE THREAD

**Issue by cailing12** [IoTSharp/EntityFrameworkCore.Taos#241]
![image](https://user-images.githubusercontent.com/22025778/206962520-31ef5998-4ee4-4ba9-b572-bb38e08af53e.png)

使用ADO.Net TaosConnection时正常，使用taoscontext时报错，版本：3.0.20

**Comment by maikebing** [comment]
是不是在使用ef core 的时候 会出这个问题？

**Comment by cailing12** [comment]
是的，运行example里的efcore例子也会报这个错




------------------&nbsp;原始邮件&nbsp;------------------
发件人:                                                                                                                        "IoTSharp/EntityFrameworkCore.Taos"                                                                                    ***@***.***&gt;;
发送时间:&nbsp;2022年12月12日(星期一) 晚上10:08
***@***.***&gt;;
***@***.******@***.***&gt;;
主题:&nbsp;Re: [IoTSharp/EntityFrameworkCore.Taos] 使用taoscontext时报错 (Issue #241)





 
是不是在使用ef core 的时候 会出这个问题？

**Comment by maikebing** [comment]
是有这个问题。  还没找到具体原因
