### ISSUE TITLE
Invalid paramter name, but No parameter.

### ISSUE THREAD

**Issue by bnuzhouwei** [IoTSharp/EntityFrameworkCore.Taos#242]
![1671271004783](https://user-images.githubusercontent.com/17919741/208236379-8665bffa-ce1a-42b7-a57e-3e38050ad6cd.png)

**Comment by maikebing** [comment]
有没有错误示例？

**Comment by bnuzhouwei** [comment]
![reader](https://user-images.githubusercontent.com/17919741/208236669-d106938d-7db4-4112-a5c5-be40533497fa.png)

我用单元测试里面跑没问题，但是在网站中跑出现这种

**Comment by bnuzhouwei** [comment]
![微信截图_20221217180943](https://user-images.githubusercontent.com/17919741/208236773-5c377a3a-8c82-41f0-8f76-fc2ac2d78181.png)

**Comment by maikebing** [comment]
sql语句在 taos的shell 里执行有没有问题

**Comment by bnuzhouwei** [comment]
sql语句在 taos的shell 里执行没有问题，在单元测试代码中也没问题，在网站中动态跑就出问题了，怀疑是不是访问了保护的内存等问题导致的？

**Comment by bnuzhouwei** [comment]
您看看，单元测试能通过：
![微信截图_20221217182407](https://user-images.githubusercontent.com/17919741/208237275-88ea1e85-5010-4f4f-abec-1256217bdbfa.png)

**Comment by bnuzhouwei** [comment]
![微信截图_20221217183023](https://user-images.githubusercontent.com/17919741/208237543-a3a8ecaa-30d7-48f8-8299-6b8d70f1cee1.png)
还是有问题，好像是内存问题导致的

**Comment by bnuzhouwei** [comment]
应该是DataReader.Load的方法导致有内存问题出现，如果不调用Load方法的话，能通过测试，否则就不行

**Comment by bnuzhouwei** [comment]
ExecuteReader 很奇怪的问题

```trace
System.Exception: Invalid parameters
 ---> IoTSharp.Data.Taos.TaosException (0x80000118): Invalid parameters
   at IoTSharp.Data.Taos.TaosException.ThrowExceptionForStmt(String _step, String _commandText, Int32 _code, IntPtr _stmt)
   at IoTSharp.Data.Taos.TaosCommand.ExecuteReader(CommandBehavior behavior, IntPtr _taos)
   at IoTSharp.Data.Taos.TaosCommand.ExecuteReader(CommandBehavior behavior)
   at System.Data.Common.DbCommand.ExecuteReader()
```

**Comment by maikebing** [comment]
我也没看出来个所以然。

**Comment by maikebing** [comment]
应该是类型没搞对导致的。
