### ISSUE TITLE
是否支持使用RESTful方式连接到TDengine Cloud？

### ISSUE THREAD

**Issue by jinwenjie98** [IoTSharp/EntityFrameworkCore.Taos#244]
是否支持使用RESTful方式连接到TDengine Cloud？

**Comment by maikebing** [comment]
支持。 websocket

**Comment by jinwenjie98** [comment]
我看到 TaosConnectionStringBuilder 中有 UseWebSocket() 方法
但是TDengine没有提供username等参数而是提供了token

![image](https://user-images.githubusercontent.com/59432060/218672852-4206c2af-fc9b-4ac7-848a-e0794908caa0.png)

我不知道如何构建ConnectionString

**Comment by maikebing** [comment]
哎呀， 我没这个账号， 没试过呀。

**Comment by jinwenjie98** [comment]
![image](https://user-images.githubusercontent.com/59432060/218677248-88dc8ea7-7437-4996-82f6-a0e3ba19fc68.png)

代码提示Keyword Not Supported，看来目前是无法连接到TDengine Cloud

**Comment by maikebing** [comment]
没有 测试账号， 没法测试， 理论上 是可以。   你扫码进微信群  加我微信 提供一个账号？

**Comment by maikebing** [comment]
我注册一个看看

**Comment by jinwenjie98** [comment]
https://cloud.tdengine.com/login

Email: wxixixixixi@aol.com
Password: xA123456

辛苦测试看看

**Comment by maikebing** [comment]
已经测试， 有点其他问题， 处理完随后发新版本

**Comment by maikebing** [comment]
新版本已经发布。 

```
  var builder_cloud = new TaosConnectionStringBuilder()
            {
                DataSource = "gw.us-east.azure.cloud.tdengine.com",
                DataBase = "iotsharp",
                Username = "root",
                Password = "taosdata",
                Token = "*******************************",
                Port = 80,
                PoolSize = 20
            };
 
 builder_cloud.UseCloud_DSN()
```
